name: Тестовые Сценарии

on:
  push:
    branches: Lab11

jobs:
  TestCases:
    runs-on: ubuntu-latest
    steps:
      - name: Выгрузка
        uses: actions/checkout@v3
      
      - name: Настройка JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Компиляция и Запуск
        run: |
          cd $GITHUB_WORKSPACE/
          kotlinc TestCases.kt -include-runtime -d out/app.jar
          echo "Main-Class: TestCasesKt" > out/manifest.txt
          java -jar out/app.jar
